### ISSUE TITLE
A bug in the module

### ISSUE THREAD

**Issue by vrurg** [thundergnat/Gray-Code-RBC#1]
I'm running some tests over the ecosystem and found a bug in the module. Sub `gray-decode` defines its return value as `Int` but returns a `Str` instance. To fix it line 9 must be either `$n.Int` or `+$n`.

**Comment by thundergnat** [comment]
Hmm. The problem was actually incorrectly implemented coercion signatures. Or more accurately, a half-assed attempt on my part to use coercion signatures without fully understanding how they should be used.

Fixed with commits 236125ec5dc4922ec771f962a22b3ef4fdab796e and 09bbc37ce208c95b74c8d71d8551c9d6fdf95d6c

Expanded testing to explicitly test passing String or Int arguments.

Thanks
